# Generated by Django 4.1 on 2022-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_scale', models.IntegerField(blank=True, null=True)),
                ('card_def', models.IntegerField(blank=True, null=True)),
                ('card_linkval', models.IntegerField(blank=True, null=True)),
                ('card_race', models.CharField(blank=True, max_length=20, null=True)),
                ('card_linkmarkers', models.CharField(blank=True, max_length=50, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('card_id', models.IntegerField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_archetype', models.CharField(blank=True, max_length=50, null=True)),
                ('card_atk', models.IntegerField(blank=True, null=True)),
                ('card_level', models.IntegerField(blank=True, null=True)),
                ('card_attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('card_images', models.CharField(blank=True, max_length=500, null=True)),
                ('card_desc', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
