# Generated by Django 4.1.1 on 2022-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_linkval', models.IntegerField()),
                ('card_race', models.CharField(max_length=20)),
                ('card_linkmarkers', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=50)),
                ('card_id', models.IntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('card_archetype', models.CharField(max_length=50)),
                ('card_attribute', models.CharField(max_length=50)),
            ],
        ),
    ]
